package noshow.vo;

public class Restaurant {
	private String businessId; /* 점주 회원 아이디 */
	private int businessNum; /* 사업자 번호 */
	private String businessName; /* 음식점 명 */
	
	
}

/*
RESTAURANT_TEL VARCHAR2(20),  음식점전화번호 
RESTAURANT_FIELD VARCHAR2(30),  업종 
RESTAURANT_HOLIDAY VARCHAR2(10),  휴무일 
RESTAURANT_OPEN DATE,  OPEN 시간 
RESTAURANT_CLOSE DATE,  CLOSE시간 
RESTAURANT_IMG VARCHAR2(500),  사진이름 
RESTAURANT_SAVE_IMG VARCHAR2(500),  저장이름 
RESTAURANT_LOCATION VARCHAR2(300),  음식점위치 
RESTAURANT_LOCATION_LATITUDE NUMBER,  위도 
RESTAURANT_LOCATION_LONGITUDE NUMBER,  경도 
RESTAURANT_CAPACITY NUMBER,  수용가능인원 
RESTAURANT_DEPOSIT NUMBER,  1인 금액 
CONSTRAINT PK_RESTAURANTB PRIMARY KEY (BUSINESS_ID)*/